# axis
正确的理解方式：axis 指的是“沿着哪个轴移动/压缩”，而不是“结果留在哪”。
> 看到 axis，就在心里默念：0 是行（竖着干），1 是列（横着干）。

- axis=0 是垂直向下移动。你从上往下扫过所有行，把行压扁了，所以它针对的是行。
- axis=1 是水平向右移动。你从左往右扫过所有列，把列压扁了，所以它针对的是列。

# [[]]
> df['列名'] 是把这列“抽”出来（变细了），df[['列名']] 是把这个表格“裁”出一列（依然是表格）。
- 在你的代码中，如果你只是想知道平均值，用单括号 df['wind'].mean() 更简洁；如果你想把结果赋给另一个变量并保留列名，就用双括号。

# map
负责做映射。

# 数据分析
## 数据导入、导出

In [131]:
import json

import pandas as pd
import numpy as np

In [4]:
# 数据导入
df = pd.read_csv('data/employees.csv')
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [5]:
# 数据的导出
df = df.tail(20)
df.to_csv('data/new.csv')

In [13]:
# json
df = pd.read_json('data/test.json')

with open('data/test.json') as f:
    json_data = json.load(f)
print(type(json_data))
print(json_data)
df = pd.DataFrame(json_data[
    'users'
                  ])
df

<class 'dict'>
{'users': [{'id': 1, 'name': '张三', 'age': 28, 'email': 'zhangsan@example.com', 'is_active': True, 'join_date': '2022-03-15'}, {'id': 2, 'name': '李四', 'age': 35, 'email': 'lisi@example.com', 'is_active': False, 'join_date': '2021-11-02'}, {'id': 3, 'name': '王五', 'age': 24, 'email': 'wangwu@example.com', 'is_active': True, 'join_date': '2023-01-20'}]}

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

## 缺失值处理
1. 查看缺失值【是否有缺失值、查看缺失值个数】
2. 剔除缺失值
3. 缺失值填充【字典填充、统计值填充、前后填充】

In [35]:
# 缺失值的处理
# nan = not a number

s = pd.Series([1, 2, np.nan, None, pd.NA])
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 4], [None, 4, 6]], columns=['a', 'b', 'c'])
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())
print(df.isna().sum(axis = 1))  # 查看缺失值的个数
print(s.isna().sum())   # 查看缺失值的总数

# 剔除缺失值
print(s.dropna())
print(df.dropna())      # 含有na数据的内容，整条数据全部删除
print(df.dropna(how='all')) # 如果所有的值都是缺失值，删除这一行
print(df.dropna(thresh=2))          # 如果至少有n个值不是缺失值，就保留
print(df.dropna(axis=1,))           # axis = 1 作用于列
df.dropna(subset=['a'])             # 如果某列有缺失值，则删除这一行

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
       a      b      c
0  False   True  False
1  False  False  False
2   True  False  False
       a      b      c
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64
3
0    1
1    2
dtype: object
     a  b  c
1  2.0  3  4
     a     b  c
0  1.0  <NA>  2
1  2.0     3  4
2  NaN     4  6
     a     b  c
0  1.0  <NA>  2
1  2.0     3  4
2  NaN     4  6
   c
0  2
1  4
2  6

     a     b  c
0  1.0  <NA>  2
1  2.0     3  4

In [ ]:
# 填充缺失值【字典填充、统计值填充、前后填充】
df = pd.read_csv('data/weather_withna.csv')
print(df.isna().sum(axis = 0))
df.head()
# 字典填充
df.fillna({'temp_max': 20, 'wind': 2.5})     # 将temp_max为na的值改为默认20
# 使用统计值来填充
df.fillna(df[['temp_max', 'wind']].mean()).tail()           # 【用平均值来填充】
# 前后填充
df.ffill().tail()           # front使用前面的来填充
df.bfill().tail()           # back使用后面的来填充

In [50]:
# 重复值的处理
data = {
    'name': ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    'age': [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA'],
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

## 去重

In [54]:
df.duplicated()         # 一整条记录都是一样的，标记为重复，返回True
df.drop_duplicates(subset= 'name')    # 去重，可以选择根据的子集subset
df.drop_duplicates(subset= 'name', keep= 'last')    # 去重，可以选择保存的位置keep

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

## 数据类型转换

In [87]:
# 数据类型转换【astype()】
df = pd.read_csv('data/sleep.csv')

df['age'] = df['age'].astype('int16')
df['gender'] = df['gender'].astype('category')      # 转为目录类型category

df['is_male'] = df['gender'].map({'Female': True, 'Male': False})
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [True, False]

## 数据变形
1. 宽表变长表、长表变宽表
    1. melt(df, id_vars, var_name, value_name)：（id_vars: 不变的列名，var_name：需要改变的列， value_name:选择谁做value）
    2. pivot(df, index, columns, values)：
2. 分列df['name'].str.split('', expend = True): expend=true会将内容来分列

In [64]:
# 数据变形【melt、pivot】
data = {
    'ID': [1, 2],
    'name': ['alice',  'bob'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89],
}
df = pd.DataFrame(data)
df.T                        # 行列转置
df

             0    1
ID           1    2
name     alice  bob
Math        90   85
English     88   92
Science     95   89

In [83]:
# melt宽表转换为长表（id_vars: 不变的列名，var_name：需要改变的列， value_name:选择谁做value）
df2 = pd.melt(df, id_vars=['ID', 'name'], var_name='subjects', value_name='score')
df2.sort_values('name')
print(df2)

   ID   name subjects  score
0   1  alice     Math     90
1   2    bob     Math     85
2   1  alice  English     88
3   2    bob  English     92
4   1  alice  Science     95
5   2    bob  Science     89

In [86]:
# pivot长表转宽表
df3 = pd.pivot(df2, index = ['ID', 'name'], columns = 'subjects', values = 'score')
print(df3)

subjects  English  Math  Science
ID name
1  alice       88    90       95
2  bob         92    85       89

In [102]:
data = {
    'ID': [1, 2],
    'name': ['alice smith', 'bob smith'],
    'Math': [90, 85],
    'English': [88, 92],
    'Science': [95, 89],
}
df = pd.DataFrame(data)

# 分列
df[['first_name', 'last_name']] = df['name'].str.split(" ", expand = True)
df = pd.read_csv('data/sleep.csv')
df = df[['person_id', 'blood_pressure']]
df[['high', 'low']] = df['blood_pressure'].str.split('/', expand = True)
df['high'] = df['high'].astype('int64')
df['low'] = df['low'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   person_id       400 non-null    int64
 1   blood_pressure  400 non-null    object
 2   high            400 non-null    int64
 3   low             400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

## 数据分箱
### 等份切分
1. pd.cut(x, bins, labels)
2. x：要处理的一维数组、Series 或 DataFrame 列。
3. bins：分段规则，有两种写法：
    - 整数：表示等宽分箱的数量（如 bins=4 会把数据按值域等分成4段）。
    - 序列（列表/数组）：自定义分割点（如 [0, 18, 35, 60, 100] 会生成 [0,18], [18,35], [35,60], [60,100] 四个区间）。
4. labels（可选）：给每个区间起一个名字（如 ['少年', '青年', '中年', '老年']）。如果不提供，默认返回的是区间范围字符串（如 (18, 35]）。
------
- 如果你只是想简单地把年龄、收入、评分等连续变量转换成分类变量，pd.cut() 就是你的首选工具。
- 如果你想给区间起名字，记得用 labels 参数，这样后续分析和可视化会清晰很多。
- 如果数据有边界值问题，检查一下 right 和 include_lowest 参数是否设置正确。【左开右闭】
### 等频切分
1. pd.qcut(x, q, labels)
- x：一维数组或 Series。
- q：整数（如 q=4 表示四分位数，q=10 表示十分位数）或分位数列表（如 [0, 0.25, 0.5, 0.75, 1]，和 q=4 等价）。
- labels：和 pd.cut() 一样，可以给区间起名字。如果不传，默认返回区间范围（如 (32.5, 57.5]）。

In [127]:
df = pd.read_csv('data/employees.csv')
df1 = df.head(10)[['employee_id', 'salary']]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [128]:
pd.cut(df1['salary'], bins= 3)
pd.cut(df1['salary'], bins= 3).value_counts()
pd.cut(df1['salary'], bins= [0, 10000, 20000, 30000])
pd.cut(df1['salary'], bins= [0, 10000, 20000, 30000]).value_counts()
pd.cut(df1['salary'], bins= [0, 10000, 20000, 30000], labels=['low', 'mid', 'high']).value_counts()

salary
(12000.0, 24000.0]    4
(4199.999, 6000.0]    3
(6000.0, 12000.0]     3
Name: count, dtype: int64

In [129]:
# 等频拆分
pd.qcut(df1['salary'], 3).value_counts()

salary
(12000.0, 24000.0]    4
(4199.999, 6000.0]    3
(6000.0, 12000.0]     3
Name: count, dtype: int64

## 杂项方法
1. df.rename()
2. df.set_index()
3. df.reset_index()

In [138]:
df = pd.DataFrame({
    'name': ['alice', 'bob', 'jack', 'alice', 'jack'],
    'age': [26, 25, 30, 25, 35],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
})
df.set_index('name', inplace=True)      # 设置索引index，设置了inplace，直接在df中操作
df.reset_index(inplace=True)            # 重置index
df.rename(columns={'age': '年龄'}, index= {0 : 4})

    name  年龄  gender
4  alice  26    Male
1    bob  25  Female
2   jack  30    Male
3  alice  25  Female
4   jack  35    Male

## 时间处理
1. 常用属性
2. 常用方法
3. 日期转换【dataFrame、csv】
4. 时间间隔
5. pd.date_range()

In [143]:
# 时间数据的处理
d1 = pd.Timestamp('2026-08-08 0:35')
d2 = pd.Timestamp('2026-09-08 13:35')
print(d)
print(type(d))
print('年：', d.year)
print('月：', d.month)
print('日：', d.day)
print(d.hour, d.minute, d.second)
print(d.quarter)        # 季度
print(d.is_month_end)   # 月底

2026-08-08 00:35:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
年： 2026
月： 8
日： 8
0 35 0
3
False

In [152]:
# 方法
print(d1.day_name())    # 周几
print(d2.weekday(), d2.day_name())     # 周几
print(d1.to_period('D'))    # 转为天数
print(d1.to_period('Q'))    # 转为季度
# 字符串转换为日期类型
a = pd.to_datetime('2025-02-28 10:00')
print(a, type(a))

Saturday
1 Tuesday
2026-08-08
2026Q3
2025-02-28 10:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [161]:
# dataFrame 日期转换
df = pd.DataFrame({
    'sales': [100, 200, 300],
    'date': ['20250601', '20260602', '20260603'],
})

df['datetime'] = pd.to_datetime(df['date'])
print(df.info())
df['week'] = df['datetime'].dt.day_name()
df['datetime'].dt.year
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      object
 2   datetime  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 204.0+ bytes
None

   sales      date   datetime       week
0    100  20250601 2025-06-01     Sunday
1    200  20260602 2026-06-02    Tuesday
2    300  20260603 2026-06-03  Wednesday

In [167]:
# csv 日期转换
df = pd.read_csv('data/weather.csv', parse_dates=['date'])      # parse_dates解析为date类型
# df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.6+ KB

In [172]:
# 日期数据作为索引
# df.set_index('date', inplace=True)      # 直接对原数据进行处理
print(df.loc['2013-01': '2013-02'])

            precipitation  temp_max  temp_min  wind  weather
date
2013-01-01            0.0       5.0      -2.8   2.7      sun
2013-01-02            0.0       6.1      -1.1   3.2      sun
2013-01-03            4.1       6.7      -1.7   3.0     rain
2013-01-04            2.5      10.0       2.2   2.8     rain
2013-01-05            3.0       6.7       4.4   3.1     rain
2013-01-06            2.0       7.2       2.8   3.0     rain
2013-01-07            2.3      10.0       4.4   7.3     rain
2013-01-08           16.3      11.7       5.6   6.3     rain
2013-01-09           38.4      10.0       1.7   5.1     rain
2013-01-10            0.3       3.3      -0.6   2.1     snow
2013-01-11            0.0       2.8      -2.8   1.9  drizzle
2013-01-12            0.0       2.8      -3.9   2.0      sun
2013-01-13            0.0       2.2      -4.4   1.5      sun
2013-01-14            0.0       3.3      -2.2   1.3      sun
2013-01-15            0.0       6.7      -0.6   2.3      sun
2013-01-16            0.0       6.1      -3.9   1.8  drizzle
2013-01-17            0.0       3.9      -2.8   1.0  drizzle
2013-01-18            0.0       3.3      -1.1   1.3  drizzle
2013-01-19            0.0       1.1      -0.6   1.9  drizzle
2013-01-20            0.0       3.3      -0.6   2.1  drizzle
2013-01-21            0.0       2.2      -1.7   1.1  drizzle
2013-01-22            0.0       3.3      -1.7   0.6  drizzle
2013-01-23            5.1       7.2       2.2   3.1     rain
2013-01-24            5.8       7.2       1.1   2.6     rain
2013-01-25            3.0      10.6       2.8   2.1     rain
2013-01-26            2.3       8.3       3.9   4.5     rain
2013-01-27            1.8       5.6       3.9   4.5     rain
2013-01-28            7.9       6.1       3.3   3.2     rain
2013-01-29            4.3       8.3       5.0   3.9     rain
2013-01-30            3.6       8.9       6.7   3.9     rain
2013-01-31            3.0       9.4       7.2   4.0     rain
2013-02-01            0.3      11.7       5.0   2.9     rain
2013-02-02            0.0       6.1       2.8   2.0  drizzle
2013-02-03            2.3       8.9       2.8   2.9     rain
2013-02-04            0.0      10.6       6.7   2.6     rain
2013-02-05            3.3      10.0       6.7   5.1     rain
2013-02-06            1.0      10.6       6.1   4.5     rain
2013-02-07            1.3       9.4       3.3   4.1     rain
2013-02-08            0.0       7.8       2.2   1.3      sun
2013-02-09            0.3       8.3       4.4   1.3     rain
2013-02-10            0.0       8.9       1.7   2.0  drizzle
2013-02-11            0.3       8.3       4.4   1.4     rain
2013-02-12            1.0      11.1       7.2   5.6     rain
2013-02-13            2.3       9.4       7.2   4.1     rain
2013-02-14            1.0       9.4       5.6   2.2     rain
2013-02-15            0.0      13.3       5.0   2.4  drizzle
2013-02-16            0.0      11.1       3.9   5.6     rain
2013-02-17            0.0       9.4       4.4   3.4     rain
2013-02-18            0.0       7.8       3.9   1.9     rain
2013-02-19            0.0      10.6       1.7   3.4      sun
2013-02-20            1.5       7.8       1.1   2.1     rain
2013-02-21            0.5       6.7       3.9   6.2     rain
2013-02-22            9.4       7.8       3.9   8.1     rain
2013-02-23            0.3      10.0       3.9   4.6     rain
2013-02-24            0.0       8.9       5.0   5.5     rain
2013-02-25            2.3      10.6       3.3   7.1     rain
2013-02-26            0.5       8.9       3.9   3.8     rain
2013-02-27            4.6      10.0       4.4   1.8     rain
2013-02-28            8.1      11.7       6.7   3.8     rain

In [174]:
# 时间间隔
d1 = pd.Timestamp('2013-01-15')
d2 = pd.Timestamp('2013-02-23')
d3 = d2 - d1
print(d3)
print(type(d3))         # 时间间隔Timedelta

39 days 00:00:00
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>

In [176]:
df = pd.read_csv('data/weather.csv', parse_dates=['date'])
df.info()
df['delta'] = df['date'] - df['date'][0]
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.6+ KB

           date  precipitation  temp_max  temp_min  wind  weather     delta
0    2012-01-01            0.0      12.8       5.0   4.7  drizzle    0 days
1    2012-01-02           10.9      10.6       2.8   4.5     rain    1 days
2    2012-01-03            0.8      11.7       7.2   2.3     rain    2 days
3    2012-01-04           20.3      12.2       5.6   4.7     rain    3 days
4    2012-01-05            1.3       8.9       2.8   6.1     rain    4 days
...         ...            ...       ...       ...   ...      ...       ...
1456 2015-12-27            8.6       4.4       1.7   2.9     rain 1456 days
1457 2015-12-28            1.5       5.0       1.7   1.3     rain 1457 days
1458 2015-12-29            0.0       7.2       0.6   2.6      fog 1458 days
1459 2015-12-30            0.0       5.6      -1.0   3.4      sun 1459 days
1460 2015-12-31            0.0       5.6      -2.1   3.5      sun 1460 days

[1461 rows x 7 columns]

In [181]:
days = pd.date_range('2025-07-03', '2026-02-09', freq = 'W')      # freq频率
days = pd.date_range('2025-07-03', periods = 10, freq = 'W')      # periods=10,取10个时间
days

DatetimeIndex(['2025-07-06', '2025-07-13', '2025-07-20', '2025-07-27',
               '2025-08-03', '2025-08-10', '2025-08-17', '2025-08-24',
               '2025-08-31', '2025-09-07'],
              dtype='datetime64[ns]', freq='W-SUN')

In [182]:
# 根据时间重新采样
df = pd.read_csv('data/weather.csv', parse_dates=['date'])
df.set_index('date', inplace=True)

In [188]:
print(df[['temp_min', 'temp_max']].resample('YE').mean())
print(df[['temp_min', 'temp_max']].resample('YS').mean())

            temp_min   temp_max
date
2012-12-31  7.289617  15.276776
2013-12-31  8.153973  16.058904
2014-12-31  8.662466  16.995890
2015-12-31  8.835616  17.427945
            temp_min   temp_max
date
2012-01-01  7.289617  15.276776
2013-01-01  8.153973  16.058904
2014-01-01  8.662466  16.995890
2015-01-01  8.835616  17.427945

## 分组聚合
> 先分组，再聚合
1. groupby('分组的字段')['聚合的字段'].聚合函数()

In [201]:
df = pd.read_csv('data/employees.csv')
print(df['department_id'].isna().sum())     # 只有一行，可以直接删掉
df.dropna(subset=['department_id'], inplace=True)
df['department_id'] = df['department_id'].astype('int64')
df.info()

1
<class 'pandas.core.frame.DataFrame'>
Index: 106 entries, 0 to 106
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   employee_id     106 non-null    int64
 1   first_name      106 non-null    object
 2   last_name       106 non-null    object
 3   email           106 non-null    object
 4   phone_number    106 non-null    object
 5   job_id          106 non-null    object
 6   salary          106 non-null    float64
 7   commission_pct  34 non-null     float64
 8   manager_id      105 non-null    float64
 9   department_id   106 non-null    int64
dtypes: float64(3), int64(2), object(5)
memory usage: 9.1+ KB

In [209]:
# 计算不同部门的平均薪资
# 分组
df.groupby('department_id').groups      # 查看分组
df.groupby('department_id').get_group(10)   # 查看具体的某个分组数据
# 分组聚合
df2 = df.groupby('department_id')['salary'].mean().round(2)       # round()保留几位小数
df2.reset_index()

    department_id    salary
0              10   4400.00
1              20   9500.00
2              30   4150.00
3              40   6500.00
4              50   3475.56
5              60   5760.00
6              70  10000.00
7              80   8955.88
8              90  19333.33
9             100   8600.00
10            110  10150.00

In [211]:
# 计算不同部门、不同岗位的人的平均薪资
df.groupby(['department_id', 'job_id']).groups
df.groupby(['department_id', 'job_id'])['salary'].mean()

department_id  job_id
10             AD_ASST        4400.000000
20             MK_MAN        13000.000000
               MK_REP         6000.000000
30             PU_CLERK       2780.000000
               PU_MAN        11000.000000
40             HR_REP         6500.000000
50             SH_CLERK       3215.000000
               ST_CLERK       2785.000000
               ST_MAN         7280.000000
60             IT_PROG        5760.000000
70             PR_REP        10000.000000
80             SA_MAN        12200.000000
               SA_REP         8396.551724
90             AD_PRES       24000.000000
               AD_VP         17000.000000
100            FI_ACCOUNT     7920.000000
               FI_MGR        12000.000000
110            AC_ACCOUNT     8300.000000
               AC_MGR        12000.000000
Name: salary, dtype: float64